# Change these first
owner: BBaoVanC # Your GitHub username
repo: status.bbaovanc.com # Your GitHub repository name

# Add your sites here
sites:
  - name: Main Site
    url: https://bbaovanc.com
  - name: Searx
    url: https://searx.bbaovanc.com
  - name: Gitea
    url: https://git.bbaovanc.com
  - name: Images
    url: https://img.bbaovanc.com
  - name: Drone CI
    url: https://drone.bbaovanc.com/bbaovanc/pynamegen
  - name: Media
    url: https://media.bbaovanc.com/test

status-website:
  theme: ocean
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.bbaovanc.com
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: bbaovanc status
  introTitle: "Status of all my websites."
  #introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  graphs: "1 1 1 1 1"
  responseTime: "1 1 1 1 1"
  staticSite: "1 1 1 1 1"
  summary: "1 1 1 1 1"
  updateTemplate: "1 1 1 1 1"
  updates: "1 1 1 1 1"
  uptime: "1 1 1 1 1"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
